include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionhandlerimpl_classic_unit
SRC_FILES = \
        ../../../../source/m2mconnectionhandler.cpp \

TEST_SRC_FILES = \
        main.cpp \
        m2mconnectionhandlerimpl_classic_test.cpp \
        test_m2mconnectionhandlerimpl_classic.cpp \
       ../../../../../../unittests/stub/m2mconnectionhandlerpimpl_stub.cpp \
       ../../../../../../unittests/stub/m2mconnectionsecurity_stub.cpp \
       ../../../../../../unittests/stub/m2mstring_stub.cpp \

include ../MakefileWorker.mk

