include ../makefile_defines.txt

COMPONENT_NAME = m2mobjectinstance_unit
SRC_FILES = \
    ../../../../source/m2mobjectinstance.cpp\
    ../../../../source/m2mstringbufferbase.cpp

TEST_SRC_FILES = \
    main.cpp\
    m2mobjectinstancetest.cpp\
    test_m2mobjectinstance.cpp\
    ../../../../../unittests/stub/m2mbase_stub.cpp\
    ../../../../../unittests/stub/m2mbase_stub.cpp\
    ../../../../../unittests/stub/m2mresource_stub.cpp\
    ../../../../../unittests/stub/m2mresourcebase_stub.cpp\
    ../../../../../unittests/stub/m2mresourceinstance_stub.cpp\
    ../../../../../unittests/stub/common_stub.cpp\
    ../../../../../unittests/stub/m2mtlvserializer_stub.cpp\
    ../../../../../unittests/stub/m2mtlvdeserializer_stub.cpp\
    ../../../../../unittests/stub/m2mreporthandler_stub.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2mtimer_stub.cpp\
    ../../../../../unittests/stub/m2mobject_stub.cpp\
    ../../../../../unittests/stub/nsdlaccesshelper_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp

include ../MakefileWorker.mk
