include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionsecurity_unit
SRC_FILES = \
        ../../../../source/m2mconnectionsecurity.cpp \

TEST_SRC_FILES = \
        main.cpp \
        m2mconnectionsecurity_mbedtlstest.cpp \
        test_m2mconnectionsecurity_mbedtls.cpp \
        ../../../../../../unittests/stub/m2mstring_stub.cpp \
        ../../../../../../unittests/stub/m2mtimer_stub.cpp \
        ../../../../../../unittests/stub/m2mbase_stub.cpp \
        ../../../../../../unittests/stub/m2mobject_stub.cpp \
        ../../../../../../unittests/stub/m2msecurity_stub.cpp \
        ../../../../../../unittests/stub/mbedtls_stub.cpp \
        ../../../../../../unittests/stub/m2mconnectionhandler_stub.cpp \
        ../../../../../../unittests/stub/m2mconnectionsecuritypimpl_stub.cpp \
        ../../../../../../unittests/stub/m2mstringbufferbase_stub.cpp \
        ../../../../../../unittests/stub/nsdlaccesshelper_stub.cpp \


include ../MakefileWorker.mk
