include ../makefile_defines.txt

COMPONENT_NAME = m2mmap_unit

SRC_FILES = \
    ../../../../source/m2mstring.cpp

TEST_SRC_FILES = \
    main.cpp\
    test_m2mmap.cpp\
    m2mmaptest.cpp

include ../MakefileWorker.mk


