include ../makefile_defines.txt

COMPONENT_NAME = m2mreporthandler_unit
SRC_FILES = \
    ../../../../source/m2mreporthandler.cpp

TEST_SRC_FILES = \
    main.cpp\
    m2mreporthandlertest.cpp\
    test_m2mreporthandler.cpp\
    ../../../../../unittests/stub/m2mtimer_stub.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp

include ../MakefileWorker.mk
