include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionsecuritypimpl_unit
SRC_FILES = \
        ../../../../source/m2mconnectionsecuritypimpl.cpp \

TEST_SRC_FILES = \
        main.cpp \
        m2mconnectionsecuritypimpl_mbedtlstest.cpp \
        test_m2mconnectionsecuritypimpl_mbedtls.cpp \
        ../../../../../../unittests/stub/m2mstring_stub.cpp \
        ../../../../../../unittests/stub/m2mtimer_stub.cpp \
        ../../../../../../unittests/stub/m2mbase_stub.cpp \
        ../../../../../../unittests/stub/m2mobject_stub.cpp \
        ../../../../../../unittests/stub/m2msecurity_stub.cpp \
        ../../../../../../unittests/stub/mbedtls_stub.cpp \
        ../../../../../../unittests/stub/m2mconnectionhandler_stub.cpp \
        ../../../../../../unittests/stub/m2mconnectionsecurity_stub.cpp \
        ../../../../../../unittests/stub/m2mstringbufferbase_stub.cpp \
        ../../../../../../unittests/stub/nsdlaccesshelper_stub.cpp \
        ../../../../../../unittests/stub/pal_tls_stub.cpp \
        ../../../../../../unittests/stub/pal_crypto_stub.cpp \
        ../../../../../../unittests/stub/m2mdevice_stub.cpp \
        ../../../../../../unittests/stub/m2minterfacefactory_stub.cpp \
        ../../../../../../unittests/stub/m2msecurity_stub.cpp \

include ../MakefileWorker.mk
