include ../makefile_defines.txt

COMPONENT_NAME = m2mstring_unit
SRC_FILES = \
    ../../../../source/m2mstring.cpp

TEST_SRC_FILES = \
    main.cpp\
    test_m2mstring.cpp\
    m2mstringtest.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp

include ../MakefileWorker.mk
