include ../makefile_defines.txt

COMPONENT_NAME = m2mtimerimpl_linux_unit
SRC_FILES = \
        ../../../../source/m2mtimerpimpl.cpp

TEST_SRC_FILES = \
        main.cpp \
        m2mtimerpimpl_classic_test.cpp \
        test_m2mtimerpimpl_classic.cpp \
        ../../../../../../unittests/stub/ns_hal_init_stub.cpp \
        ../../../../../../unittests/stub/eventOS_stub.cpp \

include ../MakefileWorker.mk

