include ../makefile_defines.txt

COMPONENT_NAME = m2mstringbufferbase_unit
SRC_FILES = \
    ../../../../source/m2mstringbufferbase.cpp

TEST_SRC_FILES = \
    main.cpp\
    m2mstringbufferbasetest.cpp\
    test_m2mstringbufferbase.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp

include ../MakefileWorker.mk
