include ../makefile_defines.txt

COMPONENT_NAME = nsdlaccesshelper_unit
SRC_FILES = \
    ../../../../source/nsdlaccesshelper.cpp

TEST_SRC_FILES = \
    main.cpp\
    nsdlaccesshelpertest.cpp\
    test_nsdlaccesshelper.cpp\
    ../../../../../unittests/stub/common_stub.cpp\
    ../../../../../unittests/stub/m2mnsdlinterface_stub.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2mconnectionhandler_stub.cpp\
    ../../../../../unittests/stub/m2mconnectionsecurity_stub.cpp\
    ../../../../../unittests/stub/m2mserver_stub.cpp\
    ../../../../../unittests/stub/m2mbase_stub.cpp\
    ../../../../../unittests/stub/m2mobject_stub.cpp\
    ../../../../../unittests/stub/m2mstringbufferbase_stub.cpp\
    ../../../../../unittests/stub/m2mtimer_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp


include ../MakefileWorker.mk
