include ../makefile_defines.txt

COMPONENT_NAME = m2mblockmessage_unit
SRC_FILES = \
    ../../../../source/m2mblockmessage.cpp

TEST_SRC_FILES = \
    main.cpp\
    m2mblockmessagetest.cpp\
    test_m2mblockmessage.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp


include ../MakefileWorker.mk
