include ../makefile_defines.txt

COMPONENT_NAME = m2minterfaceimpl_unit
SRC_FILES = \
    ../../../../source/m2minterfaceimpl.cpp\
    ../../../../source/m2mstringbufferbase.cpp

TEST_SRC_FILES = \
    main.cpp\
    m2minterfaceimpltest.cpp\
    test_m2minterfaceimpl.cpp\
    ../../../../../unittests/stub/m2mobject_stub.cpp\
    ../../../../../unittests/stub/m2mbase_stub.cpp\
    ../../../../../unittests/stub/m2mobject_stub.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2mresource_stub.cpp\
    ../../../../../unittests/stub/m2mresourcebase_stub.cpp\
    ../../../../../unittests/stub/m2mresourceinstance_stub.cpp\
    ../../../../../unittests/stub/m2mobjectinstance_stub.cpp\
    ../../../../../unittests/stub/m2msecurity_stub.cpp\
    ../../../../../unittests/stub/m2mtimer_stub.cpp\
    ../../../../../unittests/stub/m2mnsdlinterface_stub.cpp\
    ../../../../../unittests/stub/m2mconnectionhandler_stub.cpp\
    ../../../../../unittests/stub/m2mconnectionsecurity_stub.cpp\
    ../../../../../unittests/stub/nsdlaccesshelper_stub.cpp\
    ../../../../../unittests/stub/m2mserver_stub.cpp\
    ../../../../../unittests/stub/randLIB_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp

include ../MakefileWorker.mk
