include ../makefile_defines.txt

COMPONENT_NAME = uriqueryparser_unit
SRC_FILES = \
    ../../../../source/uriqueryparser.cpp

TEST_SRC_FILES = \
    main.cpp\
    uriqueryparsertest.cpp\
    test_uriqueryparser.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp

include ../MakefileWorker.mk
