include ../makefile_defines.txt

COMPONENT_NAME = m2mresourceinstance_unit
SRC_FILES = \
    ../../../../source/m2mstringbufferbase.cpp\
    ../../../../source/m2mresourceinstance.cpp\
    ../../../../source/m2mresourcebase.cpp\
    ../../../../source/m2mcallbackstorage.cpp

TEST_SRC_FILES = \
    main.cpp\
    ../../../../../unittests/stub/m2mbase_stub.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2mtimer_stub.cpp\
    ../../../../../unittests/stub/m2mreporthandler_stub.cpp\
    ../../../../../unittests/stub/common_stub.cpp\
    ../../../../../unittests/stub/m2mtlvdeserializer_stub.cpp\
    ../../../../../unittests/stub/m2mblockmessage_stub.cpp\
    ../../../../../unittests/stub/m2mobjectinstance_stub.cpp\
    ../../../../../unittests/stub/nsdlaccesshelper_stub.cpp\
    ../../../../../unittests/stub/m2mresource_stub.cpp\
    ../../../../../unittests/stub/m2mobject_stub.cpp\
    ../../../../../unittests/stub/m2mtlvserializer_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp\
    m2mresourceinstancetest.cpp\
    test_m2mresourceinstance.cpp

include ../MakefileWorker.mk
