include ../makefile_defines.txt

COMPONENT_NAME = m2mnsdlinterface_unit
SRC_FILES = \
    ../../../../source/m2mnsdlinterface.cpp\
    ../../../../source/m2mstringbufferbase.cpp

TEST_SRC_FILES = \
    main.cpp\
    m2mnsdlinterfacetest.cpp\
    test_m2mnsdlinterface.cpp\
    ../../../../../unittests/stub/m2mbase_stub.cpp\
    ../../../../../unittests/stub/m2mobject_stub.cpp\
    ../../../../../unittests/stub/m2mserver_stub.cpp\
    ../../../../../unittests/stub/m2mresource_stub.cpp\
    ../../../../../unittests/stub/m2mresourcebase_stub.cpp\
    ../../../../../unittests/stub/m2mresourceinstance_stub.cpp\
    ../../../../../unittests/stub/m2mobjectinstance_stub.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2msecurity_stub.cpp\
    ../../../../../unittests/stub/m2mconnectionsecurity_stub.cpp\
    ../../../../../unittests/stub/m2mconnectionhandler_stub.cpp\
    ../../../../../unittests/stub/m2mtimer_stub.cpp\
    ../../../../../unittests/stub/common_stub.cpp\
    ../../../../../unittests/stub/nsdlaccesshelper_stub.cpp\
    ../../../../../unittests/stub/m2mtlvserializer_stub.cpp\
    ../../../../../unittests/stub/m2mtlvdeserializer_stub.cpp\
    ../../../../../unittests/stub/m2mdevice_stub.cpp\
    ../../../../../unittests/stub/m2minterfacefactory_stub.cpp\
    ../../../../../unittests/stub/uriqueryparser_stub.cpp\
    ../../../../../unittests/stub/m2mblockmessage_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp

include ../MakefileWorker.mk
