include ../makefile_defines.txt

COMPONENT_NAME = sn_grs_unit

#This must be changed manually
SRC_FILES = \
        ../../../../source/sn_grs.c

TEST_SRC_FILES = \
        main.cpp \
        sn_grstest.cpp \
        test_sn_grs.c \
        ../../../../../../unittests/stub/sn_coap_protocol_stub.c \
        ../../../../../../unittests/stub/sn_coap_parser_stub.c \
        ../../../../../../unittests/stub/sn_coap_builder_stub.c \
        ../../../../../../unittests/stub/sn_nsdl_stub.c \
        ../../../../../../unittests/stub/ns_list_stub.c \

include ../MakefileWorker.mk

