include ../makefile_defines.txt

COMPONENT_NAME = m2mbase_unit
SRC_FILES = \
    ../../../../source/m2mbase.cpp\
    ../../../../source/m2mstringbufferbase.cpp\
    ../../../../source/m2mcallbackstorage.cpp

TEST_SRC_FILES = \
    main.cpp\
    m2mbasetest.cpp\
    test_m2mbase.cpp\
    ../../../../../unittests/stub/m2mreporthandler_stub.cpp\
    ../../../../../unittests/stub/nsdlaccesshelper_stub.cpp\
    ../../../../../unittests/stub/m2mresource_stub.cpp\
    ../../../../../unittests/stub/m2mresourcebase_stub.cpp\
    ../../../../../unittests/stub/m2mresourceinstance_stub.cpp\
    ../../../../../unittests/stub/m2mstring_stub.cpp\
    ../../../../../unittests/stub/m2mtimer_stub.cpp\
    ../../../../../unittests/stub/m2mobject_stub.cpp\
    ../../../../../unittests/stub/m2mobjectinstance_stub.cpp\
    ../../../../../unittests/stub/m2mresource_stub.cpp\
    ../../../../../unittests/stub/mbed_trace_stub.cpp\
    ../../../../../unittests/stub/m2mcorememory_stub.cpp\

include ../MakefileWorker.mk
